platform :ios, '8.0'
use_frameworks!

target 'SignDemo' do
  pod 'AFNetworking'
  pod 'MJExtension'
  # pod 'SDWebImage', '~> 3.8.2'
  pod 'SDWebImage', '~> 5.0.6'
  pod 'IQKeyboardManager'
  pod 'Toast', '~> 4.0.0'
  pod 'MJRefresh'
  pod 'Masonry'
  pod 'HRLivingBodyDetection/GHSdkLib',:path=>'../../HRLivingBodyDetection'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ARCHS'] = "arm64 armv7"
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
